### PR TITLE
Add a field to indicate if the contact is starred

### LINKED ISSUE #90: Can't get starred contact data!
Can't check if contact item is starred!
Can implement this feature for android, but have no knowledge to do it for IOS.

### PR DESCRIPTION
**Pull request by johnf**
Note: This only works on Android as Apple doesn't provide this
information :(

I read CONTRIBUTING.md after I created the patch, so not sure if you will want to merge this given it is Android only.

Fixes #90

### CODE REVIEW

**Comment by morenoh149** [comment]
is there a way to add this so that it makes sense to ios users?

**Comment by johnf** [comment]
I don't think so. From what I've found online, on iOS the star capability is part of the contacts app and not the API, so isn't accessible by other applications.

**Comment by johnf** [comment]
@morenoh149 any interest in this or should I close it?

**Comment by johnf** [comment]
@morenoh149 I've added something in. I've given you edit permissions to this PR so you can make changes as needed

**Comment by morenoh149** [comment]
there are some ios and android only things, I added them to the new readme section.

**Comment by yanivbs** [comment]
Hi,
I don't have any solution for this yet, but if you feel the need to close
it then close.

-- 

B.R

 Yaniv Ben shetrit

 Cell: 053-7276021

E-mail: ***@***.***




בתאריך יום ד׳, 15 ביוני 2022, 11:32, מאת John Ferlito ‏<
***@***.***>:

**Pull request merged**
