### PR TITLE
Feature: Search contacts by multiple phone numbers

### PR DESCRIPTION
**Pull request by Goutam192002**

### CODE REVIEW

**Comment by morenoh149** [comment]
nice, could you add the new api to the readme. Then I can begin looking into the ios version.

**Comment by Goutam192002** [comment]
Have updated the readme

**Comment by a-eid** [comment]
@Goutam192002 are u planning on adding ios support too ?

**Comment by Goutam192002** [comment]
I do not have experience with iOS..would be great if someone can contribute

**Pull request closed without merging**
