### PR TITLE
Intended case insensitive by searching collate #555

### LINKED ISSUE #555: Contact search insensitive
I would like how to make search case insensitive using methods
* getContactsMatchingString
* getContactsByEmailAddress

### PR DESCRIPTION
**Pull request by yelena870513**
Related to  Close #555 
* Applying collate nocase
* It fails at russian cheks

### CODE REVIEW

**Comment by morenoh149** [comment]
I don't think you need collate, `like` already matches caseinsensitive

**Comment by yelena870513** [comment]
> I don't think you need collate, `like` already matches caseinsensitive

You are right @morenoh149. I believe is related to device(Xiaomi brand) and localization of device (focused locales such as ru_RU(Cirilic alphabet)). You may close issue and pull request. I consider it solved. Best regards

**Comment by morenoh149** [comment]
do you think the lib needs this PR. Happy to merge if it improves the lib.

**Comment by yelena870513** [comment]
> do you think the lib needs this PR. Happy to merge if it improves the lib.

I believe it needs further research, because right now blockers in case sensitive search is bound to device and language. I need more information to correlate collate and Android specific database. I think no need more action besides this for the moment. If so in future will open a new PR with a proper explanation. Will move this comment to issue to get record

**Pull request closed without merging**
