### PR TITLE
Add functionality to open edit contact form

### PR DESCRIPTION
**Pull request by iarif123**
Add functionality to open edit contact form when an existing contact is supplied to `openContactForm()`

### CODE REVIEW

**Comment by morenoh149** [comment]
@iarif123 do you know if it's possible to do that same on iOS?

**Comment by bjacog** [comment]
@morenoh149 I'm looking into doing the same for iOS as well.

**Comment by morenoh149** [comment]
@iarif123 please attach a screenshot of what this does. This may be in the codebase already as openContactForm https://github.com/rt2zz/react-native-contacts#api

**Comment by bjacog** [comment]
@morenoh149 The existing form allows for adding a new contact, but not updating an existing contact. This PR adds the ability to open the contact form with the contact details supplied and it is an editing action instead of creating a new contact.

I have added the same feature to iOS but there is a problem I'm still working on and no tests yet.
If you are interested you can checkout https://github.com/bjacog/react-native-contacts
I have also had to add a listener for contacts changing to know when the user has edited a contact. On Android this can be achieved with an AppState listener as a new intent is launched but on iOS we are presenting a ViewController so the user never left the app.

I am no objective-c expert, any cc is welcomed, especially regarding handling viewcontrollers.

If anyone has experience with viewControllers and the actions shown at the top, I would appreciate any guidance as to how you get a cancel button to appear. You have on on the contact form, but when I launch the same viewController with forContact, there is no cancel button.

**Comment by bjacog** [comment]
@iarif123 I had ran into problems using the contact edit on react-native@0.55.4 and had to add:
`editIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);`
Before the editIntent is started.

I'm not sure why the error did not happen before, as it seems it should have complained about this earlier.

**Pull request closed without merging**
