### PR TITLE
Migrate to new Arch

### PR DESCRIPTION
**Pull request by hoanghai9650**
Migrate library to new Arch of React Native.

### CODE REVIEW

**Comment by iMJumpmxn** [comment]
I'm getting the Error while building you Branch: 

`Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CNContactViewController", referenced from:
       in react_native_contacts[3](RCTContacts.o)
ld: symbol(s) not found for architecture arm64`

**Comment by hoanghai9650** [comment]
Screenshot 2024-05-21 at 17 05 32
Have you set arm64 in excluded Architectures in Build Settings?

**Comment by morenoh149** [comment]
@hoanghai9650 thanks for this. Does this close #736 ?

**Comment by hoanghai9650** [comment]
@morenoh149 Yes, this PR will close that issue

**Comment by mym0404** [comment]
@hoanghai9650 why should we exclude arm64 architecture? It seems not an idle solution.

**Comment by hoanghai9650** [comment]
@morenoh149 As you can see in my code, I didn't config or enable any arm64, but don't know why this new arch required that, I think because of new Spec of React Native. But with all libs that I migrated to new arch, I also have to enable arm64 to make it run.

**Comment by hoanghai9650** [comment]
@mym0404  As you can see in my code, I didn't config or enable any arm64, but don't know why this new arch required that, I think because of new Spec of React Native. But with all libs that I migrated to new arch, I also have to enable arm64 to make it run.

**Comment by mym0404** [comment]
It makes sound. But, the build will success with manually add Contacts apple sdk in app target.

I'll further investigate why new arch made change.

**Comment by morenoh149** [comment]
@hoanghai9650 new conflicts

**Comment by SolankiYogesh3500** [comment]
new update on this guys ?

**Comment by faljabi** [comment]
Hi,

When this will be merged? app is crashing for new Arch.

**Pull request merged**
