### PR TITLE
Add instant message information support

### PR DESCRIPTION
**Pull request by BeHotSiii**
I added the usage of the instant message address fields.

While working on it, I discovered a little bug with my previous PR #490 which I got rid of

### CODE REVIEW

**Comment by morenoh149** [comment]
so this is just more information being returned? anything we should document here?

**Comment by BeHotSiii** [comment]
Exactly. I could add an example to the **Example Contact Record** if you want

**Comment by morenoh149** [comment]
please do

**Comment by BeHotSiii** [comment]
done

**Pull request merged**
