### PR TITLE
Fix the birthday format bug on some Android devices

### PR DESCRIPTION
**Pull request by yqbk**
The app crashed on my Android phone with European birth date format in some of my contacts.

### CODE REVIEW

**Comment by morenoh149** [comment]
what exactly does this change? could you add an comment saying
```java
// handle european '2012-12-01' -> '2012-12-01'
```
with example strings for the scenario you encountered.

**Comment by yqbk** [comment]
The application has crashed once it met contact with the birthdate in format '26.02.1969'. As I understand the code only handles the date in the US format. Unfortunately, my fix to the code is not 100% complete since it still crashed on some devices.

[Here](https://cl.ly/3J333Z2B3w3c) is the screenshot of the error that I've got on one of the devices. I think it's still connected with the date format and string handling.

**Comment by morenoh149** [comment]
seems related to the `loadContactsFrom` function at https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L263

could read the function and see if it's erroring out there? I'll add your international date format to the test app.

**Comment by zhengjingt** [comment]
some Samsung devices have this format 'Jun 20, 1988'
Putting try-catch to prevent crashing for now, but we wont be able to use users contacts

**Comment by morenoh149** [comment]
I don't you can skip if it fails, you could probably wrap in a try catch and handle the error. I'll be looking into this issue after adding an example to the project.

**Pull request closed without merging**
