### PR TITLE
feat: add group functionality

### LINKED ISSUE #747: IOS groups
Hi, there are currently 2 good modules to work with contacts, this one and https://github.com/joshuapinter/react-native-unified-contacts

Is it possible to add groups functionality to this project?
I really like simplicity of this module and ability to display native contact form on IOS
Would be good to add groups support to compensate for lack of isStarred
With groups we could create app specific group to persist favourites, or attempt to parse existing groups to detect default favourites, without it this data will be lost after reinstall

### PR DESCRIPTION
**Pull request by mrpmohiburrahman**
This PR partially addresses [issue #747](https://github.com/morenoh149/react-native-contacts/issues/747).

### Implemented Changes
Added getGroups() function which returns an array of group objects, including identifier and name

### Request for Feedback
I would appreciate feedback from the maintainers on whether I am heading in the right direction and if I should proceed with the implementation of other functions.

### Planned Functions

Below are the additional functions I am considering implementing:

- getGroup(groupId) - Returns the group matching the provided groupId.
- contactsInGroup(groupId) - Retrieves all contacts within a specified group.
- addGroup(groupDetails) - Adds a new group.
- updateGroup(groupId, updatedDetails) - Updates an existing group's details.
- deleteGroup(groupId) - Deletes a group by groupId.
- addContactsToGroup(groupId, contactIds) - Adds contacts to a group.
- removeContactsFromGroup(groupId, contactIds) - Removes specified contacts from a group.

### Question for Maintainers

Given the number of planned functions, would you prefer that I create separate PRs for each function, or include all of them in this PR?

closes #747

### CODE REVIEW

**Comment by morenoh149** [comment]
Thanks. Regarding your questions, lets put all those functions into one PR. Will you submit another PR or add the functions into this PR?

**Comment by mrpmohiburrahman** [comment]
> Thanks. Regarding your questions, lets put all those functions into one PR. Will you submit another PR or add the functions into this PR?

I will add other functions into this pr. Give me a day.

**Comment by mrpmohiburrahman** [comment]
> Thanks. Regarding your questions, lets put all those functions into one PR. Will you submit another PR or add the functions into this PR?

Hi, @morenoh149 , 

I have implemented all the required functions and updated the documentation in the README.md file.

Please review the changes at your convenience. Let me know if any further modifications are needed.

**Comment by morenoh149** [comment]
lgtm

**Pull request merged**
