### PR TITLE
Add number to an existing contact

### PR DESCRIPTION
**Pull request by Jonnyboy85**
Hello guys,
I added the "editExistingContact" method to add a number to an existing contact.
I created the method for both android and ios. I'm not an Objective-C expert and I hope I have done a good job.

Jonny

### CODE REVIEW

**Comment by Jonnyboy85** [comment]
Hi I have fixed Objective c code to correctly return the modified contact callback

**Comment by morenoh149** [comment]
Looks good! Add it to the readme and demonstrate its usage in the example app.

**Comment by Jonnyboy85** [comment]
Hi @morenoh149  I entered the required changes. I ask you to test the sample app, where I added a TextInput to discriminate the display / modification of contacts, from the new number addition feature.

**Comment by Jonnyboy85** [comment]
hi @morenoh149, do you have news regarding this feature?
thanks Jonny

**Comment by morenoh149** [comment]
Lgtm

**Pull request merged**
