### PR TITLE
Added Dates to Android Contact Provider

### PR DESCRIPTION
**Pull request by RobTS**
As referenced in #171, birthdays and other dates were missing from this library on Android. This PR adds them as contact.dates with according type labels. It is based on the work from https://github.com/wix/react-native-paged-contacts.

Tested and working.

### CODE REVIEW

**Comment by morenoh149** [comment]
First time hearing about https://github.com/wix/react-native-paged-contacts is there any reason to keep our project if that one works well?

**Comment by npomfret** [comment]
Its worth looking into certainly.

**Comment by RobTS** [comment]
I feel this project has gotten more consistent maintenance for a longer period, so personally, I favor this one.

**Comment by morenoh149** [comment]
could add integration tests for this PR on https://github.com/morenoh149/react-native-contacts-test/ simply surface the address info. See https://github.com/morenoh149/react-native-contacts-test/pull/2 for the approach.

**Comment by prtkkmrsngh** [comment]
Currently, only fetching contacts is supported with [https://github.com/wix/react-native-paged-contacts](https://github.com/wix/react-native-paged-contacts)

**Comment by morenoh149** [comment]
needs conflicts fixed. Also 3 years old. please update to reopen.

**Comment by fgarcilazo** [comment]
@morenoh149 linking you to the mentioned PR.

**Comment by morenoh149** [comment]
@fgarcilazo as I mentioned above. The PR needs to be resubmitted against the current master.

**Pull request closed without merging**
